### ISSUE TITLE
os.uname() function not working in Windows

### ISSUE THREAD

**Issue by lmalma** [yonatan-mitmit/onium#11]
In the file code.py at line 370, the following variable appears:

```
uname = os.uname()
```
I would like to point out that on the Windows platform, the uname method does not work, and it raises the following error:

`AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?`
Therefore, the code will not work on Windows. Please be aware of this.
you can use `platform.uname()`
Thank you for everything.

**Comment by yonatan-mitmit** [comment]
Hi.
I don't have access to test on a Windows machine these days.
Can you delete line 370 and replace line 371 with 
`    if _platform == 'darwin':`

Let me know if it works, I'll issue a patch..
