### ISSUE TITLE
crash on "onium edit" in CentOS 7

### ISSUE THREAD

**Issue by Danielionin** [yonatan-mitmit/onium#3]
when running the command "onium edit" in terminal, the app crashes with the following output:

Killing slack process Pid:11282.
Killing slack process Pid:11284.
Killing slack process Pid:11398.
Killing slack process Pid:11471.
Killing slack process Pid:11479.
Killing slack process Pid:11576.
Backup app.asar as /usr/bin/resources/app.asar.orig.
Traceback (most recent call last):
  File "/home/daniel/.local/bin/onium", line 11, in <module>
    sys.exit(main())
  File "/home/daniel/.local/lib/python2.7/site-packages/onium/code.py", line 417, in main
    args.func(args, app_path, asar_path)
  File "/home/daniel/.local/lib/python2.7/site-packages/onium/code.py", line 281, in do_edit_method
    shutil.copy(asar_file, backup_file)
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/bin/resources/app.asar'

In CentOS 7, the "app.asar" file is located in:
/usr/lib/slack/resources/app.asar

further more, an interesting side effect after the app crashes, when i run it again as
"onium inject"

the injection does not take place and there is no RTL support at all.

**Comment by tomgrossman** [comment]
same here on ubuntu 16.04

**Comment by yonatan-mitmit** [comment]
Sorry the delayed response. I must have incorrectly set github email notification, cause I didn't get any note here. 
As for the issue, unfortunately, I do not have access now to a Linux box to test it, but the fix looks very simple. 
in code.py there's a function called find_app_path if you can submit a PR that works on centos/ubuntu, I'll happily integrate. I'll also my Linux collaborator if they can adjust the function.
Thanks!
