### ISSUE TITLE
RTL directionality stopped working 

### ISSUE THREAD

**Issue by asaf4747** [yonatan-mitmit/onium#4]
Been using Onium for a few weeks, satisfied.
Since yesterday I noticed the RTL directionality is back to the previous mess it does by default, suspect Onium does not influence it anymore.

Could be that Slack has updated itself to a new version.
Version from About screen: Direct Download 3.3.0 64-bit

**Comment by yonatan-mitmit** [comment]
Hi.
Sorry for the delayed response. Email setting in github was incorrect.
Onium has two modes, edit and inject (default).

If you use edit, it edits Slacks internal files, which makes the changes persistent, but you need to re-run it whenever slack version changes (once every couple of weeks). That's how I use it in my computers.

Inject needs to reinject the code each time you load slack, but shouldn't care about version updates. 
The injected javascript code is the same in all cases.

Please let me know if this helps.

**Comment by asaf4747** [comment]
Thanks Yonatan.
Is there any way to create some sort of batch file that will save the hassle and just injects/edits Onium to Slack automatically each time the system starts?

**Comment by yonatan-mitmit** [comment]
I don't currently provide but such a batch but looking at alternative ways to persist the changes. For now, you can look at https://stackoverflow.com/questions/16087694/auto-run-a-bat-script-in-windows-7-at-login as easy ways of automatically running scripts at login time.

Best of luck, I'll update the readme when I add persistence
