### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by chocolate012** [yonatan-mitmit/onium#7]
I installed it but the app is still not RTL anyway to debug or how to go about it?

**Comment by cr-mitmit** [comment]
Slack had a minor release yesterday that broke the RTL fix. I updated Onium to support the most recent version.

Please try again.

**Comment by chocolate012** [comment]
yes it works
Thanks

**Comment by chocolate012** [comment]
Is there any way I can contact you?

**Comment by cr-mitmit** [comment]
Through here is ideal.

**Comment by chocolate012** [comment]
I was wondering if you can take this another step and add Hebrew in the app for the menus and other builtin wordings

**Comment by cr-mitmit** [comment]
Likely possible to replace individual words, but it's likely a lot of work.
Not sure I understand the motivation - can you elaborate?

**Comment by chocolate012** [comment]
We just started using Slack in our Non-Profit organization and a lot of the members will feel more comfortable if we can have Slack in Hebrew

**Comment by cr-mitmit** [comment]
Sorry. I don't see any chance to undertake such a large project anytime soon.
If you have the programming skills, I can point you to what needs to be done.

**Comment by chocolate012** [comment]
I don't have but if you can point me in the right direction. it will be easier to find someone
Thanks


--

**Comment by cr-mitmit** [comment]
Onium allows running with `-d` which allows a chrome process to debug it. Run `onium -d` and then launch slack and chrome. In Chrome browse to `http://localhost:9222/` and then you can see the raw "code" of the page.

At that point you need to find the text and change onium's `code.py` to modify the slack program.

**Comment by chocolate012** [comment]
If I understand correctly this will only allow me to modify the wordings within the Slack app but not the words that are within Slack, correct?

**Comment by cr-mitmit** [comment]
It allows you to modify the code (technically html+js code) running in the app. 
This allows you to modify the entire slack user interface.
