### ISSUE TITLE
how can I remove the plugin?

### ISSUE THREAD

**Issue by hishtadlut** [yonatan-mitmit/onium#8]
thanks for this plugin
it's very helpful

how can I remove the plugin?
I installed it on my computer for debugging but now I don't know how to remove it.

**Comment by cr-mitmit** [comment]
I didn't write an uninstall function, but it's pretty easy.

When you run it again it will show you the "backup path" (and fail the operation as the backup exists).
For example, on my mac it's on /Applications/slack.app/Contents/Resources/app.asar.orig

On the same library you'll find a file called "app.asar". You should delete app.asar and rename app.asar.orig back to app.asar

If I have time, I'll add an uninstall function. 
Additionally, simply reinstalling slack will achieve the same effect - Onium simply patches the app.asar file with the RTL support.

**Comment by cr-mitmit** [comment]
Uninstall is not possible on Macos as we need to resign the app.
