### ISSUE TITLE
Mac OS installation

### ISSUE THREAD

**Issue by river-studio-main** [yonatan-mitmit/onium#9]
Hi and thank you for you work!
I've been trying to install the Onium patch on my mac os, and received an error message as follows:
`Cannot write to /Applications/Slack.app/Contents/Resources. Run elevated.`
Any idea on how to solve this?
Thanks

**Comment by cr-mitmit** [comment]
run it with `sudo` first, as in `sudo python -m onium` 
Let me know if you have any other problem

**Comment by river-studio-main** [comment]
Thank you for your help and quick reply, this does seem to solve some issues, but others were created... The cli claims to be finished, but Slack is crashing and unable to open ("Slack quit unexpectedly"). 
Any help?
Thank you!

**Comment by cr-mitmit** [comment]
In order to understand what's going on, I need you to open a terminal and try to run slack from the command line.
Usually as `/Applications/Slack.app/Contents/MacOS/Slack` in a terminal window

**Comment by cr-mitmit** [comment]
Also, which computer are you using and which os version?

**Comment by river-studio-main** [comment]
It gives the same result when running from the terminal, outputing: 
`[88479:0112/170646.019377:FATAL:asar_util.cc(164)] Integrity check failed for asar archive (7471c5a0afdad7da16c4f38b70de292d135a98ef1914e6458c9fc01209e643df vs 311357c24568eaa09ca00e2468691d66a86d0f9bca47a5d32aae7d00b8cfe891)
[1]    88479 trace trap  /Applications/Slack.app/Contents/MacOS/Slack`

I'm using a MacBook Pro (13-inch, 2020), with macOS Big Sur 11.6.2 (20G314).

Thank you!

**Comment by cr-mitmit** [comment]
Thanks.
I fixed that issue on ARM (Apple Silicone) as in the past it wasn't needed on Mac based intel. Seems like they force it now.

Can you replace `onium.py` file with [this one](https://raw.githubusercontent.com/yonatan-mitmit/onium/resign_asar_on_macos/onium/code.py) linked below and let me know if it fixes the problem?

**Comment by cr-mitmit** [comment]
Pushed the commit that add resigning on Intel based mac too. Should close this issue.
You're welcome to verify if it works for you

**Comment by river-studio-main** [comment]
Working, brilliant :)
Thank you very much (sorry for the long response time).

**Comment by cr-mitmit** [comment]
Cool. Help spread the word :)
